- name: install base system packages
  become: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
     - python3-dev
     - python3-setuptools
     - python-virtualenv
     - libxml2-dev
     - libxslt1-dev
     - zlib1g-dev
     - libblas-dev
     - liblapack-dev
     - libatlas-base-dev
     - gfortran
     - libpq-dev
     - git

- name: create virtualenv with python3
  shell: virtualenv {{ virtualenv_path }} -p python3

- name: Install pip dependencies
  pip: virtualenv="{{ virtualenv_path }}"
    chdir="{{ local_dev_path }}"
    requirements="{{ local_dev_path }}/{{ item }}"
  with_items:
     - requirements.txt

- name: Copy dev env to local dev path
  template: src=local_env.sh.j2
            dest={{ local_dev_path }}/local_env.sh
            mode=0755

- name: Dev environment for bashrc
  lineinfile: dest=/home/vagrant/.bashrc line=". {{ local_dev_path }}/local_env.sh"

- name: Dev environment for zshrc
  lineinfile: dest=/home/vagrant/.zshrc line=". {{ app_path }}/bellhops_env.sh"
  ignore_errors: true
